GET http://localhost:5000/api HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2JhZDk2NTc5OTNhODk3ZGJkNDc4NzkiLCJpYXQiOjE2NzMxODk3NzksImV4cCI6MTY3MzE4OTc5NH0.a67Q3cjhOaK-CDoUKbfwDXIJr-OdUM8GAsKF1vv-rS0
###

POST http://localhost:5000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "farrel",
    "password": "1234569w876",
    "confPassword": "1234569w876"
}

###
POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "farrel",
    "password": "1234569w876"
}

###
GET http://localhost:5000/auth/token HTTP/1.1
Content-Type: application/json
