GET http://localhost:5000/api HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2JiOWE4MGU2Yzk5MmY0NGY3Zjk5NTUiLCJpYXQiOjE2NzMyNDE2NzksImV4cCI6MTY3MzI0MTY5NH0.s5AEveiDlis_q3R7JUzqMvcSVxdAWEHserqyh3mCYrM

###
POST http://localhost:5000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "farrel",
    "password": "1234569w876",
    "confPassword": "1234569w876"
}

###
POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "farrelarp123",
    "password": "12345678"
}

###
GET http://localhost:5000/auth/token HTTP/1.1
Content-Type: application/json
